name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clean Buildozer Cache
        run: |
          rm -rf ~/.buildozer
          rm -rf .buildozer

      # YAKUNIY TUZATISH: Libffi va Cython uchun kerakli barcha Linux paketlari o'rnatiladi
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool m4 pkg-config Build-essential
          pip install --upgrade pip
          pip install buildozer cython gitpython

      - name: Build Android APK
        run: |
          buildozer android debug